// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfqH787V8G-h2IsAWzGMMBuYr1in9d4x0',
    appId: '1:4284644868:web:8e863b861d2611d7ab3f51',
    messagingSenderId: '4284644868',
    projectId: 'smart-gift-finder',
    authDomain: 'smart-gift-finder.firebaseapp.com',
    storageBucket: 'smart-gift-finder.firebasestorage.app',
    measurementId: 'G-L0SNVLV4VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9DMAtD4wdOorZYrVHTb3WhkkFqDRXYgU',
    appId: '1:4284644868:android:5ba37d9be1497b8fab3f51',
    messagingSenderId: '4284644868',
    projectId: 'smart-gift-finder',
    storageBucket: 'smart-gift-finder.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrvfEvqNLzozmuFP9phho2HLobqY1sQc',
    appId: '1:4284644868:ios:3daa57a8a3d0661eab3f51',
    messagingSenderId: '4284644868',
    projectId: 'smart-gift-finder',
    storageBucket: 'smart-gift-finder.firebasestorage.app',
    iosBundleId: 'com.example.itiGraduationProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkrvfEvqNLzozmuFP9phho2HLobqY1sQc',
    appId: '1:4284644868:ios:3daa57a8a3d0661eab3f51',
    messagingSenderId: '4284644868',
    projectId: 'smart-gift-finder',
    storageBucket: 'smart-gift-finder.firebasestorage.app',
    iosBundleId: 'com.example.itiGraduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfqH787V8G-h2IsAWzGMMBuYr1in9d4x0',
    appId: '1:4284644868:web:01758c8eabdbba1eab3f51',
    messagingSenderId: '4284644868',
    projectId: 'smart-gift-finder',
    authDomain: 'smart-gift-finder.firebaseapp.com',
    storageBucket: 'smart-gift-finder.firebasestorage.app',
    measurementId: 'G-YEYVLB4QZB',
  );
}
